version: '3.8'
services:
  frontend:
    build: ./_fronted_angular # Ruta al Dockerfile de tu Angular app
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend # Ruta al Dockerfile de tu Spring Boot / Node app
    ports:
      - "5000:5000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/airport_db?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: airport_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: